export default {
  login: 'Vadzimka0',
  id: 47316370,
  node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
  avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Vadzimka0',
  html_url: 'https://github.com/Vadzimka0',
  followers_url: 'https://api.github.com/users/Vadzimka0/followers',
  following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
  gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
  organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
  repos_url: 'https://api.github.com/users/Vadzimka0/repos',
  events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
  type: 'User',
  site_admin: false,
  name: 'Vadzim Dzianisik',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: '2019-02-04T08:55:49Z',
  updated_at: '2021-12-08T18:04:10Z',
};
