export default [
  {
    id: 423924109,
    node_id: 'R_kgDOGUSRjQ',
    name: '11-02-redux-f',
    full_name: 'Vadzimka0/11-02-redux-f',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/11-02-redux-f',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f',
    forks_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/events',
    assignees_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/tags',
    blobs_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/languages',
    stargazers_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/stargazers',
    contributors_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/contributors',
    subscribers_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/subscribers',
    subscription_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/subscription',
    commits_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/downloads',
    issues_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/11-02-redux-f/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/labels{/name}',
    releases_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Vadzimka0/11-02-redux-f/deployments',
    created_at: '2021-11-02T16:44:27Z',
    updated_at: '2021-11-02T18:09:38Z',
    pushed_at: '2021-11-02T18:09:35Z',
    git_url: 'git://github.com/Vadzimka0/11-02-redux-f.git',
    ssh_url: 'git@github.com:Vadzimka0/11-02-redux-f.git',
    clone_url: 'https://github.com/Vadzimka0/11-02-redux-f.git',
    svn_url: 'https://github.com/Vadzimka0/11-02-redux-f',
    homepage: null,
    size: 223,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 414686098,
    node_id: 'R_kgDOGLebkg',
    name: 'art-projects',
    full_name: 'Vadzimka0/art-projects',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/art-projects',
    description: 'match-match',
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/art-projects',
    forks_url: 'https://api.github.com/repos/Vadzimka0/art-projects/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/art-projects/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/art-projects/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/art-projects/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/art-projects/events',
    assignees_url: 'https://api.github.com/repos/Vadzimka0/art-projects/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Vadzimka0/art-projects/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/art-projects/tags',
    blobs_url: 'https://api.github.com/repos/Vadzimka0/art-projects/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Vadzimka0/art-projects/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Vadzimka0/art-projects/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Vadzimka0/art-projects/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Vadzimka0/art-projects/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/art-projects/languages',
    stargazers_url: 'https://api.github.com/repos/Vadzimka0/art-projects/stargazers',
    contributors_url: 'https://api.github.com/repos/Vadzimka0/art-projects/contributors',
    subscribers_url: 'https://api.github.com/repos/Vadzimka0/art-projects/subscribers',
    subscription_url: 'https://api.github.com/repos/Vadzimka0/art-projects/subscription',
    commits_url: 'https://api.github.com/repos/Vadzimka0/art-projects/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Vadzimka0/art-projects/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Vadzimka0/art-projects/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/art-projects/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/art-projects/downloads',
    issues_url: 'https://api.github.com/repos/Vadzimka0/art-projects/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Vadzimka0/art-projects/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/art-projects/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Vadzimka0/art-projects/labels{/name}',
    releases_url: 'https://api.github.com/repos/Vadzimka0/art-projects/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Vadzimka0/art-projects/deployments',
    created_at: '2021-10-07T16:54:23Z',
    updated_at: '2021-10-07T16:54:53Z',
    pushed_at: '2021-10-07T16:54:50Z',
    git_url: 'git://github.com/Vadzimka0/art-projects.git',
    ssh_url: 'git@github.com:Vadzimka0/art-projects.git',
    clone_url: 'https://github.com/Vadzimka0/art-projects.git',
    svn_url: 'https://github.com/Vadzimka0/art-projects',
    homepage: null,
    size: 469,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 430799537,
    node_id: 'R_kgDOGa16sQ',
    name: 'color-hex-generator',
    full_name: 'Vadzimka0/color-hex-generator',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/color-hex-generator',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator',
    forks_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/events',
    assignees_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/tags',
    blobs_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/git/blobs{/sha}',
    git_tags_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/git/tags{/sha}',
    git_refs_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/git/refs{/sha}',
    trees_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/git/trees{/sha}',
    statuses_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/languages',
    stargazers_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/stargazers',
    contributors_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/contributors',
    subscribers_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/subscribers',
    subscription_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/subscription',
    commits_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/color-hex-generator/downloads',
    issues_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/issues{/number}',
    pulls_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/notifications{?since,all,participating}',
    labels_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/labels{/name}',
    releases_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/releases{/id}',
    deployments_url:
      'https://api.github.com/repos/Vadzimka0/color-hex-generator/deployments',
    created_at: '2021-11-22T17:16:17Z',
    updated_at: '2021-11-23T08:00:03Z',
    pushed_at: '2021-11-23T08:00:00Z',
    git_url: 'git://github.com/Vadzimka0/color-hex-generator.git',
    ssh_url: 'git@github.com:Vadzimka0/color-hex-generator.git',
    clone_url: 'https://github.com/Vadzimka0/color-hex-generator.git',
    svn_url: 'https://github.com/Vadzimka0/color-hex-generator',
    homepage: null,
    size: 223,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 421729948,
    node_id: 'R_kgDOGSMWnA',
    name: 'online-shop-showcase-basket',
    full_name: 'Vadzimka0/online-shop-showcase-basket',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/online-shop-showcase-basket',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket',
    forks_url: 'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/forks',
    keys_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/issues/events{/number}',
    events_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/events',
    assignees_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/tags',
    blobs_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/git/blobs{/sha}',
    git_tags_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/git/tags{/sha}',
    git_refs_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/git/refs{/sha}',
    trees_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/git/trees{/sha}',
    statuses_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/statuses/{sha}',
    languages_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/languages',
    stargazers_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/stargazers',
    contributors_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/contributors',
    subscribers_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/subscribers',
    subscription_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/subscription',
    commits_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/compare/{base}...{head}',
    merges_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/{archive_format}{/ref}',
    downloads_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/downloads',
    issues_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/issues{/number}',
    pulls_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/notifications{?since,all,participating}',
    labels_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/labels{/name}',
    releases_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/releases{/id}',
    deployments_url:
      'https://api.github.com/repos/Vadzimka0/online-shop-showcase-basket/deployments',
    created_at: '2021-10-27T08:06:31Z',
    updated_at: '2021-10-28T06:14:26Z',
    pushed_at: '2021-10-28T06:14:23Z',
    git_url: 'git://github.com/Vadzimka0/online-shop-showcase-basket.git',
    ssh_url: 'git@github.com:Vadzimka0/online-shop-showcase-basket.git',
    clone_url: 'https://github.com/Vadzimka0/online-shop-showcase-basket.git',
    svn_url: 'https://github.com/Vadzimka0/online-shop-showcase-basket',
    homepage: null,
    size: 229,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 433442870,
    node_id: 'R_kgDOGdXQNg',
    name: 'portfolio',
    full_name: 'Vadzimka0/portfolio',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/portfolio',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/portfolio',
    forks_url: 'https://api.github.com/repos/Vadzimka0/portfolio/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/portfolio/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/portfolio/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/portfolio/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/portfolio/events',
    assignees_url: 'https://api.github.com/repos/Vadzimka0/portfolio/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Vadzimka0/portfolio/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/portfolio/tags',
    blobs_url: 'https://api.github.com/repos/Vadzimka0/portfolio/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Vadzimka0/portfolio/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Vadzimka0/portfolio/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Vadzimka0/portfolio/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Vadzimka0/portfolio/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/portfolio/languages',
    stargazers_url: 'https://api.github.com/repos/Vadzimka0/portfolio/stargazers',
    contributors_url: 'https://api.github.com/repos/Vadzimka0/portfolio/contributors',
    subscribers_url: 'https://api.github.com/repos/Vadzimka0/portfolio/subscribers',
    subscription_url: 'https://api.github.com/repos/Vadzimka0/portfolio/subscription',
    commits_url: 'https://api.github.com/repos/Vadzimka0/portfolio/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Vadzimka0/portfolio/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Vadzimka0/portfolio/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Vadzimka0/portfolio/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/portfolio/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/portfolio/downloads',
    issues_url: 'https://api.github.com/repos/Vadzimka0/portfolio/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Vadzimka0/portfolio/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/portfolio/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Vadzimka0/portfolio/labels{/name}',
    releases_url: 'https://api.github.com/repos/Vadzimka0/portfolio/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Vadzimka0/portfolio/deployments',
    created_at: '2021-11-30T13:33:08Z',
    updated_at: '2021-12-07T08:44:53Z',
    pushed_at: '2021-12-07T08:45:54Z',
    git_url: 'git://github.com/Vadzimka0/portfolio.git',
    ssh_url: 'git@github.com:Vadzimka0/portfolio.git',
    clone_url: 'https://github.com/Vadzimka0/portfolio.git',
    svn_url: 'https://github.com/Vadzimka0/portfolio',
    homepage: null,
    size: 3454,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 394041277,
    node_id: 'MDEwOlJlcG9zaXRvcnkzOTQwNDEyNzc=',
    name: 'projects-repo',
    full_name: 'Vadzimka0/projects-repo',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/projects-repo',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/projects-repo',
    forks_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/events',
    assignees_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/tags',
    blobs_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/languages',
    stargazers_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/stargazers',
    contributors_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/contributors',
    subscribers_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/subscribers',
    subscription_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/subscription',
    commits_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/downloads',
    issues_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/projects-repo/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/labels{/name}',
    releases_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Vadzimka0/projects-repo/deployments',
    created_at: '2021-08-08T18:34:02Z',
    updated_at: '2021-08-11T19:26:28Z',
    pushed_at: '2021-08-11T19:26:26Z',
    git_url: 'git://github.com/Vadzimka0/projects-repo.git',
    ssh_url: 'git@github.com:Vadzimka0/projects-repo.git',
    clone_url: 'https://github.com/Vadzimka0/projects-repo.git',
    svn_url: 'https://github.com/Vadzimka0/projects-repo',
    homepage: null,
    size: 2693,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'SCSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 384556941,
    node_id: 'MDEwOlJlcG9zaXRvcnkzODQ1NTY5NDE=',
    name: 'rsschool-cv',
    full_name: 'Vadzimka0/rsschool-cv',
    private: false,
    owner: {
      login: 'Vadzimka0',
      id: 47316370,
      node_id: 'MDQ6VXNlcjQ3MzE2Mzcw',
      avatar_url: 'https://avatars.githubusercontent.com/u/47316370?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Vadzimka0',
      html_url: 'https://github.com/Vadzimka0',
      followers_url: 'https://api.github.com/users/Vadzimka0/followers',
      following_url: 'https://api.github.com/users/Vadzimka0/following{/other_user}',
      gists_url: 'https://api.github.com/users/Vadzimka0/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Vadzimka0/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Vadzimka0/subscriptions',
      organizations_url: 'https://api.github.com/users/Vadzimka0/orgs',
      repos_url: 'https://api.github.com/users/Vadzimka0/repos',
      events_url: 'https://api.github.com/users/Vadzimka0/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Vadzimka0/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Vadzimka0/rsschool-cv',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv',
    forks_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/forks',
    keys_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/teams',
    hooks_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/hooks',
    issue_events_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/events',
    assignees_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/tags',
    blobs_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/languages',
    stargazers_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/stargazers',
    contributors_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/contributors',
    subscribers_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/subscribers',
    subscription_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/subscription',
    commits_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/merges',
    archive_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/downloads',
    issues_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Vadzimka0/rsschool-cv/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/labels{/name}',
    releases_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Vadzimka0/rsschool-cv/deployments',
    created_at: '2021-07-09T21:44:18Z',
    updated_at: '2021-07-12T14:11:43Z',
    pushed_at: '2021-07-17T22:21:36Z',
    git_url: 'git://github.com/Vadzimka0/rsschool-cv.git',
    ssh_url: 'git@github.com:Vadzimka0/rsschool-cv.git',
    clone_url: 'https://github.com/Vadzimka0/rsschool-cv.git',
    svn_url: 'https://github.com/Vadzimka0/rsschool-cv',
    homepage: null,
    size: 41,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 2,
    license: null,
    allow_forking: true,
    is_template: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 2,
    watchers: 0,
    default_branch: 'main',
  },
];
